// Code generated by iplist_generate on 2022-10-21 06:19:36.019416787 +0000 UTC; DO NOT EDIT.

package cloudflare

import "net/netip"

//go:generate go run iplist_generate.go

func init() {
	iplist = append(iplist,
		netip.MustParsePrefix("173.245.48.0/20"),
		netip.MustParsePrefix("103.21.244.0/22"),
		netip.MustParsePrefix("103.22.200.0/22"),
		netip.MustParsePrefix("103.31.4.0/22"),
		netip.MustParsePrefix("141.101.64.0/18"),
		netip.MustParsePrefix("108.162.192.0/18"),
		netip.MustParsePrefix("190.93.240.0/20"),
		netip.MustParsePrefix("188.114.96.0/20"),
		netip.MustParsePrefix("197.234.240.0/22"),
		netip.MustParsePrefix("198.41.128.0/17"),
		netip.MustParsePrefix("162.158.0.0/15"),
		netip.MustParsePrefix("104.16.0.0/13"),
		netip.MustParsePrefix("104.24.0.0/14"),
		netip.MustParsePrefix("172.64.0.0/13"),
		netip.MustParsePrefix("131.0.72.0/22"),
		netip.MustParsePrefix("2400:cb00::/32"),
		netip.MustParsePrefix("2606:4700::/32"),
		netip.MustParsePrefix("2803:f800::/32"),
		netip.MustParsePrefix("2405:b500::/32"),
		netip.MustParsePrefix("2405:8100::/32"),
		netip.MustParsePrefix("2a06:98c0::/29"),
		netip.MustParsePrefix("2c0f:f248::/32"),
	)
}
